// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Player__char_32_1_555d1695bf1878941bdcea6e7bdd0b10Index = 0;
		public const int GreyboxBuilding2_32d6247132758a74088777106e059e9dIndex = 1;
		public const int Player__char_32_2_75f6611ace5a6a74daa3ea8e6a775febIndex = 2;
		public const int GreyboxBuilding_740dc65917c8b324eb303a2698f2dd1aIndex = 3;
		public const int GreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6eIndex = 4;
		public const int tree1GGJ_dcbe017ddb668d24fbbd84607bebbc08Index = 5;
		public const int tree2GGJ_6deeb2c1af05aa8418d68271a04a30d0Index = 6;
		public const int tree3GGJ_aeb6565d66e84134a8bed68b9c23a88cIndex = 7;
		public const int tree_GGJ_3bcf20e841cfdc74388cde29fa1de9baIndex = 8;
		public const int HexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327Index = 9;
		public const int Building1_b4bece24bc468c34587f46fa49fba06fIndex = 10;
		public const int building2_055f8f777c9c41a4d90ba8bc1ab22daeIndex = 11;
		public const int Building3_7a150e548341e554686c3ad454e4222cIndex = 12;
		public const int Building4_e19425375427f9b488aa3730f7396c91Index = 13;
		public const int TreeRotated_5df1f8a97e35cf4489a4be093fd1f124Index = 14;
		public const int Tree2_3d52409f49bc3ee4fbe52ae04f61f837Index = 15;
		public const int Tree3_5a772a534f3f2634fb628cceb128b128Index = 16;
		public const int Cube_6344a489f82917c4fa01c2adf8b0afd1Index = 17;
		public const int PlayerHuman_6d57491473fb68a4a87f6eca2180c0d4Index = 18;
		public const int PlayerTree_6e41740ccd468754ebce2e5459d93cddIndex = 19;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Player__char_32_1_555d1695bf1878941bdcea6e7bdd0b10", 0 },

			{ "GreyboxBuilding2_32d6247132758a74088777106e059e9d", 1 },

			{ "Player__char_32_2_75f6611ace5a6a74daa3ea8e6a775feb", 2 },

			{ "GreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a", 3 },

			{ "GreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e", 4 },

			{ "tree1GGJ_dcbe017ddb668d24fbbd84607bebbc08", 5 },

			{ "tree2GGJ_6deeb2c1af05aa8418d68271a04a30d0", 6 },

			{ "tree3GGJ_aeb6565d66e84134a8bed68b9c23a88c", 7 },

			{ "tree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba", 8 },

			{ "HexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327", 9 },

			{ "Building1_b4bece24bc468c34587f46fa49fba06f", 10 },

			{ "building2_055f8f777c9c41a4d90ba8bc1ab22dae", 11 },

			{ "Building3_7a150e548341e554686c3ad454e4222c", 12 },

			{ "Building4_e19425375427f9b488aa3730f7396c91", 13 },

			{ "TreeRotated_5df1f8a97e35cf4489a4be093fd1f124", 14 },

			{ "Tree2_3d52409f49bc3ee4fbe52ae04f61f837", 15 },

			{ "Tree3_5a772a534f3f2634fb628cceb128b128", 16 },

			{ "Cube_6344a489f82917c4fa01c2adf8b0afd1", 17 },

			{ "PlayerHuman_6d57491473fb68a4a87f6eca2180c0d4", 18 },

			{ "PlayerTree_6e41740ccd468754ebce2e5459d93cdd", 19 },

		};
	}
}
