// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Player__char_32_1_555d1695bf1878941bdcea6e7bdd0b10Index = 0;
		public const int BuildingRot_d7c48c9304a42cb4786538e9ef8284a4Index = 1;
		public const int Player__char_32_2_75f6611ace5a6a74daa3ea8e6a775febIndex = 2;
		public const int BuildingRot1_d3b68f2763ee5354ea6e20ba9fe863b6Index = 3;
		public const int BuildingRot2_e54e3390c037cdb4ea5c1b0191dd93ffIndex = 4;
		public const int TreeRot_9d98c1c2c8ca66341b697cd88abce46bIndex = 5;
		public const int TreeRot1_f3e71fd7c178b0741a7f8fa2e92e94cbIndex = 6;
		public const int TreeRot2_665e8f2632a4d3a46a693f897bb7ccaeIndex = 7;
		public const int TreeRot3_fd4e093c29f40b14ea1af5200044859cIndex = 8;
		public const int PlayerTree_6e41740ccd468754ebce2e5459d93cddIndex = 9;
		public const int PlayerHuman_6d57491473fb68a4a87f6eca2180c0d4Index = 10;
		public const int HexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327Index = 11;
		public const int GreyboxBuilding_740dc65917c8b324eb303a2698f2dd1aIndex = 12;
		public const int GreyboxBuilding2_32d6247132758a74088777106e059e9dIndex = 13;
		public const int GreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6eIndex = 14;
		public const int tree_GGJ_3bcf20e841cfdc74388cde29fa1de9baIndex = 15;
		public const int tree1GGJ_dcbe017ddb668d24fbbd84607bebbc08Index = 16;
		public const int tree2GGJ_6deeb2c1af05aa8418d68271a04a30d0Index = 17;
		public const int tree3GGJ_aeb6565d66e84134a8bed68b9c23a88cIndex = 18;
		public const int Cube_6344a489f82917c4fa01c2adf8b0afd1Index = 19;
		public const int PlanetIndividualOrigins_fb542973efeb9b8439784d3664e0003aIndex = 20;
		public const int trap__char_32_1_457588b80d22e4245966566d77356d43Index = 21;
		public const int Trap_ba06265ea0ce0496daed310dbe2a5c20Index = 22;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Player__char_32_1_555d1695bf1878941bdcea6e7bdd0b10", 0 },

			{ "BuildingRot_d7c48c9304a42cb4786538e9ef8284a4", 1 },

			{ "Player__char_32_2_75f6611ace5a6a74daa3ea8e6a775feb", 2 },

			{ "BuildingRot1_d3b68f2763ee5354ea6e20ba9fe863b6", 3 },

			{ "BuildingRot2_e54e3390c037cdb4ea5c1b0191dd93ff", 4 },

			{ "TreeRot_9d98c1c2c8ca66341b697cd88abce46b", 5 },

			{ "TreeRot1_f3e71fd7c178b0741a7f8fa2e92e94cb", 6 },

			{ "TreeRot2_665e8f2632a4d3a46a693f897bb7ccae", 7 },

			{ "TreeRot3_fd4e093c29f40b14ea1af5200044859c", 8 },

			{ "PlayerTree_6e41740ccd468754ebce2e5459d93cdd", 9 },

			{ "PlayerHuman_6d57491473fb68a4a87f6eca2180c0d4", 10 },

			{ "HexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327", 11 },

			{ "GreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a", 12 },

			{ "GreyboxBuilding2_32d6247132758a74088777106e059e9d", 13 },

			{ "GreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e", 14 },

			{ "tree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba", 15 },

			{ "tree1GGJ_dcbe017ddb668d24fbbd84607bebbc08", 16 },

			{ "tree2GGJ_6deeb2c1af05aa8418d68271a04a30d0", 17 },

			{ "tree3GGJ_aeb6565d66e84134a8bed68b9c23a88c", 18 },

			{ "Cube_6344a489f82917c4fa01c2adf8b0afd1", 19 },

			{ "PlanetIndividualOrigins_fb542973efeb9b8439784d3664e0003a", 20 },

			{ "trap__char_32_1_457588b80d22e4245966566d77356d43", 21 },

			{ "Trap_ba06265ea0ce0496daed310dbe2a5c20", 22 },

		};
	}
}
