// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_fd4e093c29f40b14ea1af5200044859c_6a362aff_6651_43fa_a71c_51d0262afb94 : StringBinding
	{
		private Coherence.Toolkit.CoherenceNode CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Coherence.Toolkit.CoherenceNode)UnityComponent;
		}
		public override string CoherenceComponentName => "TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override string Value
		{
			get => (string)(System.String)(CastedUnityComponent.path);
			set => CastedUnityComponent.path = (System.String)(value);
		}

		protected override string ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786)coherenceComponent;
			return update.path;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786)coherenceComponent;
			update.path = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786();
		}
	}

	public class Binding_fd4e093c29f40b14ea1af5200044859c_758e227b_7870_42b5_b7d6_6dc2b24091c9 : IntBinding
	{
		private Coherence.Toolkit.CoherenceNode CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Coherence.Toolkit.CoherenceNode)UnityComponent;
		}
		public override string CoherenceComponentName => "TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.pathDirtyCounter);
			set => CastedUnityComponent.pathDirtyCounter = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786)coherenceComponent;
			return update.pathDirtyCounter;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786)coherenceComponent;
			update.pathDirtyCounter = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'TreeRot3' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncTreeRot3_id8 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncTreeRot3_id8>();
			if (coherenceSync.TryGetBindingByGuid("6a362aff-6651-43fa-a71c-51d0262afb94", "path", out Binding InternalTreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_path))
			{
				var clone = new Binding_fd4e093c29f40b14ea1af5200044859c_6a362aff_6651_43fa_a71c_51d0262afb94();
				InternalTreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_path.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalTreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_path)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Coherence.Toolkit.CoherenceNode).path");
			}
			if (coherenceSync.TryGetBindingByGuid("758e227b-7870-42b5-b7d6-6dc2b24091c9", "pathDirtyCounter", out Binding InternalTreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_pathDirtyCounter))
			{
				var clone = new Binding_fd4e093c29f40b14ea1af5200044859c_758e227b_7870_42b5_b7d6_6dc2b24091c9();
				InternalTreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_pathDirtyCounter.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalTreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_pathDirtyCounter)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Coherence.Toolkit.CoherenceNode).pathDirtyCounter");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncTreeRot3_id8] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
