// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_9d98c1c2c8ca66341b697cd88abce46b_371e3adc_ca53_41ef_a28c_0103673c3987 : StringBinding
	{
		private Coherence.Toolkit.CoherenceNode CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Coherence.Toolkit.CoherenceNode)UnityComponent;
		}
		public override string CoherenceComponentName => "TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override string Value
		{
			get => (string)(System.String)(CastedUnityComponent.path);
			set => CastedUnityComponent.path = (System.String)(value);
		}

		protected override string ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981)coherenceComponent;
			return update.path;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981)coherenceComponent;
			update.path = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981();
		}
	}

	public class Binding_9d98c1c2c8ca66341b697cd88abce46b_fd8a9a27_1c89_4f16_9154_04fe259ecaaf : IntBinding
	{
		private Coherence.Toolkit.CoherenceNode CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Coherence.Toolkit.CoherenceNode)UnityComponent;
		}
		public override string CoherenceComponentName => "TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.pathDirtyCounter);
			set => CastedUnityComponent.pathDirtyCounter = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981)coherenceComponent;
			return update.pathDirtyCounter;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981)coherenceComponent;
			update.pathDirtyCounter = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'TreeRot' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncTreeRot_id5 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncTreeRot_id5>();
			if (coherenceSync.TryGetBindingByGuid("371e3adc-ca53-41ef-a28c-0103673c3987", "path", out Binding InternalTreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_path))
			{
				var clone = new Binding_9d98c1c2c8ca66341b697cd88abce46b_371e3adc_ca53_41ef_a28c_0103673c3987();
				InternalTreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_path.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalTreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_path)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Coherence.Toolkit.CoherenceNode).path");
			}
			if (coherenceSync.TryGetBindingByGuid("fd8a9a27-1c89-4f16-9154-04fe259ecaaf", "pathDirtyCounter", out Binding InternalTreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_pathDirtyCounter))
			{
				var clone = new Binding_9d98c1c2c8ca66341b697cd88abce46b_fd8a9a27_1c89_4f16_9154_04fe259ecaaf();
				InternalTreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_pathDirtyCounter.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalTreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_TreeRot_id5_Coherence__char_46_Toolkit__char_46_CoherenceNode_2223525859964372981_pathDirtyCounter)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Coherence.Toolkit.CoherenceNode).pathDirtyCounter");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncTreeRot_id5] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
