// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_e54e3390c037cdb4ea5c1b0191dd93ff_584451c8_91e2_4d59_aa2b_e8d53fae60f3 : StringBinding
	{
		private Coherence.Toolkit.CoherenceNode CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Coherence.Toolkit.CoherenceNode)UnityComponent;
		}
		public override string CoherenceComponentName => "BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override string Value
		{
			get => (string)(System.String)(CastedUnityComponent.path);
			set => CastedUnityComponent.path = (System.String)(value);
		}

		protected override string ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065)coherenceComponent;
			return update.path;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065)coherenceComponent;
			update.path = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065();
		}
	}

	public class Binding_e54e3390c037cdb4ea5c1b0191dd93ff_54fbbd40_30bf_4424_ae8e_5f153d3cb138 : IntBinding
	{
		private Coherence.Toolkit.CoherenceNode CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (Coherence.Toolkit.CoherenceNode)UnityComponent;
		}
		public override string CoherenceComponentName => "BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.pathDirtyCounter);
			set => CastedUnityComponent.pathDirtyCounter = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065)coherenceComponent;
			return update.pathDirtyCounter;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065)coherenceComponent;
			update.pathDirtyCounter = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'BuildingRot2' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncBuildingRot2_id4 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncBuildingRot2_id4>();
			if (coherenceSync.TryGetBindingByGuid("584451c8-91e2-4d59-aa2b-e8d53fae60f3", "path", out Binding InternalBuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_path))
			{
				var clone = new Binding_e54e3390c037cdb4ea5c1b0191dd93ff_584451c8_91e2_4d59_aa2b_e8d53fae60f3();
				InternalBuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_path.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_path)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Coherence.Toolkit.CoherenceNode).path");
			}
			if (coherenceSync.TryGetBindingByGuid("54fbbd40-30bf-4424-ae8e-5f153d3cb138", "pathDirtyCounter", out Binding InternalBuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_pathDirtyCounter))
			{
				var clone = new Binding_e54e3390c037cdb4ea5c1b0191dd93ff_54fbbd40_30bf_4424_ae8e_5f153d3cb138();
				InternalBuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_pathDirtyCounter.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_BuildingRot2_id4_Coherence__char_46_Toolkit__char_46_CoherenceNode_118036802855613065_pathDirtyCounter)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (Coherence.Toolkit.CoherenceNode).pathDirtyCounter");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncBuildingRot2_id4] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
