// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Connection;
	using Coherence.Entity;
	using Coherence.Serializer;
	using Coherence.Log;
	using System.Collections.Generic;

	public class Definition : IDefinition
	{
		public const string schemaId = "f8e6c803eb51769abbebc5b6bfd00f5ce4498edf";
		public const uint InternalWorldPosition = 0;
		public const uint InternalWorldOrientation = 1;
		public const uint InternalLocalUser = 2;
		public const uint InternalWorldPositionQuery = 3;
		public const uint InternalArchetypeComponent = 4;
		public const uint InternalPersistence = 5;
		public const uint InternalConnectedEntity = 6;
		public const uint InternalUniqueID = 7;
		public const uint InternalConnection = 8;
		public const uint InternalGlobal = 9;
		public const uint InternalGlobalQuery = 10;
		public const uint InternalTag = 11;
		public const uint InternalTagQuery = 12;
		public const uint InternalPreserveChildren = 13;
		public const uint InternalGenericPrefabReference = 14;
		public const uint InternalGenericPrefabId = 15;
		public const uint InternalGenericScale = 16;
		public const uint InternalGenericFieldInt0 = 17;
		public const uint InternalGenericFieldInt1 = 18;
		public const uint InternalGenericFieldInt2 = 19;
		public const uint InternalGenericFieldInt3 = 20;
		public const uint InternalGenericFieldInt4 = 21;
		public const uint InternalGenericFieldInt5 = 22;
		public const uint InternalGenericFieldInt6 = 23;
		public const uint InternalGenericFieldInt7 = 24;
		public const uint InternalGenericFieldInt8 = 25;
		public const uint InternalGenericFieldInt9 = 26;
		public const uint InternalGenericFieldUInt0 = 27;
		public const uint InternalGenericFieldUInt1 = 28;
		public const uint InternalGenericFieldUInt2 = 29;
		public const uint InternalGenericFieldUInt3 = 30;
		public const uint InternalGenericFieldUInt4 = 31;
		public const uint InternalGenericFieldUInt5 = 32;
		public const uint InternalGenericFieldUInt6 = 33;
		public const uint InternalGenericFieldUInt7 = 34;
		public const uint InternalGenericFieldUInt8 = 35;
		public const uint InternalGenericFieldUInt9 = 36;
		public const uint InternalGenericFieldBool0 = 37;
		public const uint InternalGenericFieldBool1 = 38;
		public const uint InternalGenericFieldBool2 = 39;
		public const uint InternalGenericFieldBool3 = 40;
		public const uint InternalGenericFieldBool4 = 41;
		public const uint InternalGenericFieldBool5 = 42;
		public const uint InternalGenericFieldBool6 = 43;
		public const uint InternalGenericFieldBool7 = 44;
		public const uint InternalGenericFieldBool8 = 45;
		public const uint InternalGenericFieldBool9 = 46;
		public const uint InternalGenericFieldFloat0 = 47;
		public const uint InternalGenericFieldFloat1 = 48;
		public const uint InternalGenericFieldFloat2 = 49;
		public const uint InternalGenericFieldFloat3 = 50;
		public const uint InternalGenericFieldFloat4 = 51;
		public const uint InternalGenericFieldFloat5 = 52;
		public const uint InternalGenericFieldFloat6 = 53;
		public const uint InternalGenericFieldFloat7 = 54;
		public const uint InternalGenericFieldFloat8 = 55;
		public const uint InternalGenericFieldFloat9 = 56;
		public const uint InternalGenericFieldDouble0 = 57;
		public const uint InternalGenericFieldDouble1 = 58;
		public const uint InternalGenericFieldDouble2 = 59;
		public const uint InternalGenericFieldDouble3 = 60;
		public const uint InternalGenericFieldDouble4 = 61;
		public const uint InternalGenericFieldDouble5 = 62;
		public const uint InternalGenericFieldDouble6 = 63;
		public const uint InternalGenericFieldDouble7 = 64;
		public const uint InternalGenericFieldDouble8 = 65;
		public const uint InternalGenericFieldDouble9 = 66;
		public const uint InternalGenericFieldVector0 = 67;
		public const uint InternalGenericFieldVector1 = 68;
		public const uint InternalGenericFieldVector2 = 69;
		public const uint InternalGenericFieldVector3 = 70;
		public const uint InternalGenericField2dVector0 = 71;
		public const uint InternalGenericField2dVector1 = 72;
		public const uint InternalGenericField2dVector2 = 73;
		public const uint InternalGenericField2dVector3 = 74;
		public const uint InternalGenericFieldString0 = 75;
		public const uint InternalGenericFieldString1 = 76;
		public const uint InternalGenericFieldString2 = 77;
		public const uint InternalGenericFieldString3 = 78;
		public const uint InternalGenericFieldString4 = 79;
		public const uint InternalGenericFieldQuaternion0 = 80;
		public const uint InternalGenericFieldEntity0 = 81;
		public const uint InternalGenericFieldEntity1 = 82;
		public const uint InternalGenericFieldEntity2 = 83;
		public const uint InternalGenericFieldEntity3 = 84;
		public const uint InternalGenericFieldEntity4 = 85;
		public const uint InternalGenericFieldEntity5 = 86;
		public const uint InternalGenericFieldEntity6 = 87;
		public const uint InternalGenericFieldEntity7 = 88;
		public const uint InternalGenericFieldEntity8 = 89;
		public const uint InternalGenericFieldEntity9 = 90;
		public const uint InternalGenericFieldBytes0 = 91;
		public const uint InternalGenericFieldLong0 = 92;
		public const uint InternalGenericFieldLong1 = 93;
		public const uint InternalGenericFieldLong2 = 94;
		public const uint InternalGenericFieldLong3 = 95;
		public const uint InternalGenericFieldULong0 = 96;
		public const uint InternalGenericFieldULong1 = 97;
		public const uint InternalGenericFieldULong2 = 98;
		public const uint InternalGenericFieldULong3 = 99;
		public const uint InternalGenericFieldColor0 = 100;
		public const uint InternalGenericFieldColor1 = 101;
		public const uint InternalPlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149 = 102;
		public const uint InternalPlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214 = 103;
		public const uint InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldPosition_LOD0 = 104;
		public const uint InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldOrientation_LOD0 = 105;
		public const uint InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_GenericScale_LOD0 = 106;
		public const uint InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149_LOD0 = 107;
		public const uint InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldPosition_LOD0 = 108;
		public const uint InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldOrientation_LOD0 = 109;
		public const uint InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_GenericScale_LOD0 = 110;
		public const uint InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214_LOD0 = 111;
		public const uint InternalArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldPosition_LOD0 = 112;
		public const uint InternalArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldOrientation_LOD0 = 113;
		public const uint InternalArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_GenericScale_LOD0 = 114;
		public const uint InternalArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldPosition_LOD0 = 115;
		public const uint InternalArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldOrientation_LOD0 = 116;
		public const uint InternalArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldPosition_LOD0 = 117;
		public const uint InternalArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldOrientation_LOD0 = 118;
		public const uint InternalArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldPosition_LOD0 = 119;
		public const uint InternalArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldOrientation_LOD0 = 120;
		public const uint InternalArchetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldPosition_LOD0 = 121;
		public const uint InternalArchetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldOrientation_LOD0 = 122;
		public const uint InternalArchetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldPosition_LOD0 = 123;
		public const uint InternalArchetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldOrientation_LOD0 = 124;
		public const uint InternalArchetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldPosition_LOD0 = 125;
		public const uint InternalArchetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldOrientation_LOD0 = 126;
		public const uint InternalArchetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldPosition_LOD0 = 127;
		public const uint InternalArchetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldOrientation_LOD0 = 128;
		public const uint InternalArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldPosition_LOD0 = 129;
		public const uint InternalArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldOrientation_LOD0 = 130;
		public const uint InternalArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_GenericScale_LOD0 = 131;
		public const uint InternalArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldPosition_LOD0 = 132;
		public const uint InternalArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldOrientation_LOD0 = 133;
		public const uint InternalArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_GenericScale_LOD0 = 134;
		public const uint InternalArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldPosition_LOD0 = 135;
		public const uint InternalArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldOrientation_LOD0 = 136;
		public const uint InternalArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_GenericScale_LOD0 = 137;
		public const uint InternalArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldPosition_LOD0 = 138;
		public const uint InternalArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldOrientation_LOD0 = 139;
		public const uint InternalArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_GenericScale_LOD0 = 140;
		public const uint InternalArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldPosition_LOD0 = 141;
		public const uint InternalArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldOrientation_LOD0 = 142;
		public const uint InternalArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_GenericScale_LOD0 = 143;
		public const uint InternalArchetypePlayer__char_32_1_555d1695bf1878941bdcea6e7bdd0b10_WorldPosition_LOD0 = 144;
		public const uint InternalArchetypePlayer__char_32_2_75f6611ace5a6a74daa3ea8e6a775feb_WorldPosition_LOD0 = 145;
		public const uint InternalArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldPosition_LOD0 = 146;
		public const uint InternalArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldOrientation_LOD0 = 147;
		public const uint InternalArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_GenericScale_LOD0 = 148;
		public const uint InternalArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldPosition_LOD0 = 149;
		public const uint InternalArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldOrientation_LOD0 = 150;
		public const uint InternalArchetypeTree3_5a772a534f3f2634fb628cceb128b128_GenericScale_LOD0 = 151;
		public const uint InternalArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldPosition_LOD0 = 152;
		public const uint InternalArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldOrientation_LOD0 = 153;
		public const uint InternalArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_GenericScale_LOD0 = 154;
		public const uint InternalAuthorityRequest = 0;
		public const uint InternalAuthorityTransfer = 1;
		public const uint InternalQuerySynced = 2;
		public const uint InternalAdoptOrphan = 3;
		public const uint InternalPersistenceReady = 4;
		public const uint InternalGenericCommand = 5;
		public const uint InternalPlayerHuman = 0;
		public const uint InternalPlayerTree = 1;

		private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>() {
			{ 0, "WorldPosition" },
			{ 1, "WorldOrientation" },
			{ 2, "LocalUser" },
			{ 3, "WorldPositionQuery" },
			{ 4, "ArchetypeComponent" },
			{ 5, "Persistence" },
			{ 6, "ConnectedEntity" },
			{ 7, "UniqueID" },
			{ 8, "Connection" },
			{ 9, "Global" },
			{ 10, "GlobalQuery" },
			{ 11, "Tag" },
			{ 12, "TagQuery" },
			{ 13, "PreserveChildren" },
			{ 14, "GenericPrefabReference" },
			{ 15, "GenericPrefabId" },
			{ 16, "GenericScale" },
			{ 17, "GenericFieldInt0" },
			{ 18, "GenericFieldInt1" },
			{ 19, "GenericFieldInt2" },
			{ 20, "GenericFieldInt3" },
			{ 21, "GenericFieldInt4" },
			{ 22, "GenericFieldInt5" },
			{ 23, "GenericFieldInt6" },
			{ 24, "GenericFieldInt7" },
			{ 25, "GenericFieldInt8" },
			{ 26, "GenericFieldInt9" },
			{ 27, "GenericFieldUInt0" },
			{ 28, "GenericFieldUInt1" },
			{ 29, "GenericFieldUInt2" },
			{ 30, "GenericFieldUInt3" },
			{ 31, "GenericFieldUInt4" },
			{ 32, "GenericFieldUInt5" },
			{ 33, "GenericFieldUInt6" },
			{ 34, "GenericFieldUInt7" },
			{ 35, "GenericFieldUInt8" },
			{ 36, "GenericFieldUInt9" },
			{ 37, "GenericFieldBool0" },
			{ 38, "GenericFieldBool1" },
			{ 39, "GenericFieldBool2" },
			{ 40, "GenericFieldBool3" },
			{ 41, "GenericFieldBool4" },
			{ 42, "GenericFieldBool5" },
			{ 43, "GenericFieldBool6" },
			{ 44, "GenericFieldBool7" },
			{ 45, "GenericFieldBool8" },
			{ 46, "GenericFieldBool9" },
			{ 47, "GenericFieldFloat0" },
			{ 48, "GenericFieldFloat1" },
			{ 49, "GenericFieldFloat2" },
			{ 50, "GenericFieldFloat3" },
			{ 51, "GenericFieldFloat4" },
			{ 52, "GenericFieldFloat5" },
			{ 53, "GenericFieldFloat6" },
			{ 54, "GenericFieldFloat7" },
			{ 55, "GenericFieldFloat8" },
			{ 56, "GenericFieldFloat9" },
			{ 57, "GenericFieldDouble0" },
			{ 58, "GenericFieldDouble1" },
			{ 59, "GenericFieldDouble2" },
			{ 60, "GenericFieldDouble3" },
			{ 61, "GenericFieldDouble4" },
			{ 62, "GenericFieldDouble5" },
			{ 63, "GenericFieldDouble6" },
			{ 64, "GenericFieldDouble7" },
			{ 65, "GenericFieldDouble8" },
			{ 66, "GenericFieldDouble9" },
			{ 67, "GenericFieldVector0" },
			{ 68, "GenericFieldVector1" },
			{ 69, "GenericFieldVector2" },
			{ 70, "GenericFieldVector3" },
			{ 71, "GenericField2dVector0" },
			{ 72, "GenericField2dVector1" },
			{ 73, "GenericField2dVector2" },
			{ 74, "GenericField2dVector3" },
			{ 75, "GenericFieldString0" },
			{ 76, "GenericFieldString1" },
			{ 77, "GenericFieldString2" },
			{ 78, "GenericFieldString3" },
			{ 79, "GenericFieldString4" },
			{ 80, "GenericFieldQuaternion0" },
			{ 81, "GenericFieldEntity0" },
			{ 82, "GenericFieldEntity1" },
			{ 83, "GenericFieldEntity2" },
			{ 84, "GenericFieldEntity3" },
			{ 85, "GenericFieldEntity4" },
			{ 86, "GenericFieldEntity5" },
			{ 87, "GenericFieldEntity6" },
			{ 88, "GenericFieldEntity7" },
			{ 89, "GenericFieldEntity8" },
			{ 90, "GenericFieldEntity9" },
			{ 91, "GenericFieldBytes0" },
			{ 92, "GenericFieldLong0" },
			{ 93, "GenericFieldLong1" },
			{ 94, "GenericFieldLong2" },
			{ 95, "GenericFieldLong3" },
			{ 96, "GenericFieldULong0" },
			{ 97, "GenericFieldULong1" },
			{ 98, "GenericFieldULong2" },
			{ 99, "GenericFieldULong3" },
			{ 100, "GenericFieldColor0" },
			{ 101, "GenericFieldColor1" },
			{ 102, "PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149" },
			{ 103, "PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214" },
			{ 104, "ArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldPosition_LOD0" },
			{ 105, "ArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldOrientation_LOD0" },
			{ 106, "ArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_GenericScale_LOD0" },
			{ 107, "ArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149_LOD0" },
			{ 108, "ArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldPosition_LOD0" },
			{ 109, "ArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldOrientation_LOD0" },
			{ 110, "ArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_GenericScale_LOD0" },
			{ 111, "ArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214_LOD0" },
			{ 112, "ArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldPosition_LOD0" },
			{ 113, "ArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldOrientation_LOD0" },
			{ 114, "ArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_GenericScale_LOD0" },
			{ 115, "ArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldPosition_LOD0" },
			{ 116, "ArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldOrientation_LOD0" },
			{ 117, "ArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldPosition_LOD0" },
			{ 118, "ArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldOrientation_LOD0" },
			{ 119, "ArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldPosition_LOD0" },
			{ 120, "ArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldOrientation_LOD0" },
			{ 121, "Archetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldPosition_LOD0" },
			{ 122, "Archetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldOrientation_LOD0" },
			{ 123, "Archetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldPosition_LOD0" },
			{ 124, "Archetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldOrientation_LOD0" },
			{ 125, "Archetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldPosition_LOD0" },
			{ 126, "Archetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldOrientation_LOD0" },
			{ 127, "Archetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldPosition_LOD0" },
			{ 128, "Archetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldOrientation_LOD0" },
			{ 129, "ArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldPosition_LOD0" },
			{ 130, "ArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldOrientation_LOD0" },
			{ 131, "ArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_GenericScale_LOD0" },
			{ 132, "Archetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldPosition_LOD0" },
			{ 133, "Archetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldOrientation_LOD0" },
			{ 134, "Archetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_GenericScale_LOD0" },
			{ 135, "ArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldPosition_LOD0" },
			{ 136, "ArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldOrientation_LOD0" },
			{ 137, "ArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_GenericScale_LOD0" },
			{ 138, "ArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldPosition_LOD0" },
			{ 139, "ArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldOrientation_LOD0" },
			{ 140, "ArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_GenericScale_LOD0" },
			{ 141, "ArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldPosition_LOD0" },
			{ 142, "ArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldOrientation_LOD0" },
			{ 143, "ArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_GenericScale_LOD0" },
			{ 144, "ArchetypePlayer__char_32_1_555d1695bf1878941bdcea6e7bdd0b10_WorldPosition_LOD0" },
			{ 145, "ArchetypePlayer__char_32_2_75f6611ace5a6a74daa3ea8e6a775feb_WorldPosition_LOD0" },
			{ 146, "ArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldPosition_LOD0" },
			{ 147, "ArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldOrientation_LOD0" },
			{ 148, "ArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_GenericScale_LOD0" },
			{ 149, "ArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldPosition_LOD0" },
			{ 150, "ArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldOrientation_LOD0" },
			{ 151, "ArchetypeTree3_5a772a534f3f2634fb628cceb128b128_GenericScale_LOD0" },
			{ 152, "ArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldPosition_LOD0" },
			{ 153, "ArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldOrientation_LOD0" },
			{ 154, "ArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_GenericScale_LOD0" },
		};

		public static string ComponentNameForTypeId(uint typeId)
		{
			if(componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
			{
				return componentName;
			}
			else
			{
				return "";
			}
		}

		public (ICoherenceComponentData, uint, uint?) ReadComponentUpdate(uint componentType, 
			IInBitStream bitStream, Logger logger)
		{
			var inProtocolStream = new InProtocolBitStream(bitStream);

			switch (componentType)
			{
				case InternalWorldPosition:
					return WorldPosition.Deserialize(inProtocolStream);
				case InternalWorldOrientation:
					return WorldOrientation.Deserialize(inProtocolStream);
				case InternalLocalUser:
					return LocalUser.Deserialize(inProtocolStream);
				case InternalWorldPositionQuery:
					return WorldPositionQuery.Deserialize(inProtocolStream);
				case InternalArchetypeComponent:
					return ArchetypeComponent.Deserialize(inProtocolStream);
				case InternalPersistence:
					return Persistence.Deserialize(inProtocolStream);
				case InternalConnectedEntity:
					return ConnectedEntity.Deserialize(inProtocolStream);
				case InternalUniqueID:
					return UniqueID.Deserialize(inProtocolStream);
				case InternalConnection:
					return Connection.Deserialize(inProtocolStream);
				case InternalGlobal:
					return Global.Deserialize(inProtocolStream);
				case InternalGlobalQuery:
					return GlobalQuery.Deserialize(inProtocolStream);
				case InternalTag:
					return Tag.Deserialize(inProtocolStream);
				case InternalTagQuery:
					return TagQuery.Deserialize(inProtocolStream);
				case InternalPreserveChildren:
					return PreserveChildren.Deserialize(inProtocolStream);
				case InternalGenericPrefabReference:
					return GenericPrefabReference.Deserialize(inProtocolStream);
				case InternalGenericPrefabId:
					return GenericPrefabId.Deserialize(inProtocolStream);
				case InternalGenericScale:
					return GenericScale.Deserialize(inProtocolStream);
				case InternalGenericFieldInt0:
					return GenericFieldInt0.Deserialize(inProtocolStream);
				case InternalGenericFieldInt1:
					return GenericFieldInt1.Deserialize(inProtocolStream);
				case InternalGenericFieldInt2:
					return GenericFieldInt2.Deserialize(inProtocolStream);
				case InternalGenericFieldInt3:
					return GenericFieldInt3.Deserialize(inProtocolStream);
				case InternalGenericFieldInt4:
					return GenericFieldInt4.Deserialize(inProtocolStream);
				case InternalGenericFieldInt5:
					return GenericFieldInt5.Deserialize(inProtocolStream);
				case InternalGenericFieldInt6:
					return GenericFieldInt6.Deserialize(inProtocolStream);
				case InternalGenericFieldInt7:
					return GenericFieldInt7.Deserialize(inProtocolStream);
				case InternalGenericFieldInt8:
					return GenericFieldInt8.Deserialize(inProtocolStream);
				case InternalGenericFieldInt9:
					return GenericFieldInt9.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt0:
					return GenericFieldUInt0.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt1:
					return GenericFieldUInt1.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt2:
					return GenericFieldUInt2.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt3:
					return GenericFieldUInt3.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt4:
					return GenericFieldUInt4.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt5:
					return GenericFieldUInt5.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt6:
					return GenericFieldUInt6.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt7:
					return GenericFieldUInt7.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt8:
					return GenericFieldUInt8.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt9:
					return GenericFieldUInt9.Deserialize(inProtocolStream);
				case InternalGenericFieldBool0:
					return GenericFieldBool0.Deserialize(inProtocolStream);
				case InternalGenericFieldBool1:
					return GenericFieldBool1.Deserialize(inProtocolStream);
				case InternalGenericFieldBool2:
					return GenericFieldBool2.Deserialize(inProtocolStream);
				case InternalGenericFieldBool3:
					return GenericFieldBool3.Deserialize(inProtocolStream);
				case InternalGenericFieldBool4:
					return GenericFieldBool4.Deserialize(inProtocolStream);
				case InternalGenericFieldBool5:
					return GenericFieldBool5.Deserialize(inProtocolStream);
				case InternalGenericFieldBool6:
					return GenericFieldBool6.Deserialize(inProtocolStream);
				case InternalGenericFieldBool7:
					return GenericFieldBool7.Deserialize(inProtocolStream);
				case InternalGenericFieldBool8:
					return GenericFieldBool8.Deserialize(inProtocolStream);
				case InternalGenericFieldBool9:
					return GenericFieldBool9.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat0:
					return GenericFieldFloat0.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat1:
					return GenericFieldFloat1.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat2:
					return GenericFieldFloat2.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat3:
					return GenericFieldFloat3.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat4:
					return GenericFieldFloat4.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat5:
					return GenericFieldFloat5.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat6:
					return GenericFieldFloat6.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat7:
					return GenericFieldFloat7.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat8:
					return GenericFieldFloat8.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat9:
					return GenericFieldFloat9.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble0:
					return GenericFieldDouble0.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble1:
					return GenericFieldDouble1.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble2:
					return GenericFieldDouble2.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble3:
					return GenericFieldDouble3.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble4:
					return GenericFieldDouble4.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble5:
					return GenericFieldDouble5.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble6:
					return GenericFieldDouble6.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble7:
					return GenericFieldDouble7.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble8:
					return GenericFieldDouble8.Deserialize(inProtocolStream);
				case InternalGenericFieldDouble9:
					return GenericFieldDouble9.Deserialize(inProtocolStream);
				case InternalGenericFieldVector0:
					return GenericFieldVector0.Deserialize(inProtocolStream);
				case InternalGenericFieldVector1:
					return GenericFieldVector1.Deserialize(inProtocolStream);
				case InternalGenericFieldVector2:
					return GenericFieldVector2.Deserialize(inProtocolStream);
				case InternalGenericFieldVector3:
					return GenericFieldVector3.Deserialize(inProtocolStream);
				case InternalGenericField2dVector0:
					return GenericField2dVector0.Deserialize(inProtocolStream);
				case InternalGenericField2dVector1:
					return GenericField2dVector1.Deserialize(inProtocolStream);
				case InternalGenericField2dVector2:
					return GenericField2dVector2.Deserialize(inProtocolStream);
				case InternalGenericField2dVector3:
					return GenericField2dVector3.Deserialize(inProtocolStream);
				case InternalGenericFieldString0:
					return GenericFieldString0.Deserialize(inProtocolStream);
				case InternalGenericFieldString1:
					return GenericFieldString1.Deserialize(inProtocolStream);
				case InternalGenericFieldString2:
					return GenericFieldString2.Deserialize(inProtocolStream);
				case InternalGenericFieldString3:
					return GenericFieldString3.Deserialize(inProtocolStream);
				case InternalGenericFieldString4:
					return GenericFieldString4.Deserialize(inProtocolStream);
				case InternalGenericFieldQuaternion0:
					return GenericFieldQuaternion0.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity0:
					return GenericFieldEntity0.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity1:
					return GenericFieldEntity1.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity2:
					return GenericFieldEntity2.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity3:
					return GenericFieldEntity3.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity4:
					return GenericFieldEntity4.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity5:
					return GenericFieldEntity5.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity6:
					return GenericFieldEntity6.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity7:
					return GenericFieldEntity7.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity8:
					return GenericFieldEntity8.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity9:
					return GenericFieldEntity9.Deserialize(inProtocolStream);
				case InternalGenericFieldBytes0:
					return GenericFieldBytes0.Deserialize(inProtocolStream);
				case InternalGenericFieldLong0:
					return GenericFieldLong0.Deserialize(inProtocolStream);
				case InternalGenericFieldLong1:
					return GenericFieldLong1.Deserialize(inProtocolStream);
				case InternalGenericFieldLong2:
					return GenericFieldLong2.Deserialize(inProtocolStream);
				case InternalGenericFieldLong3:
					return GenericFieldLong3.Deserialize(inProtocolStream);
				case InternalGenericFieldULong0:
					return GenericFieldULong0.Deserialize(inProtocolStream);
				case InternalGenericFieldULong1:
					return GenericFieldULong1.Deserialize(inProtocolStream);
				case InternalGenericFieldULong2:
					return GenericFieldULong2.Deserialize(inProtocolStream);
				case InternalGenericFieldULong3:
					return GenericFieldULong3.Deserialize(inProtocolStream);
				case InternalGenericFieldColor0:
					return GenericFieldColor0.Deserialize(inProtocolStream);
				case InternalGenericFieldColor1:
					return GenericFieldColor1.Deserialize(inProtocolStream);
				case InternalPlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149:
					return PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149.Deserialize(inProtocolStream);
				case InternalPlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214:
					return PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214.Deserialize(inProtocolStream);
				case InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149_LOD0:
					return PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149.DeserializeArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149_LOD0(inProtocolStream);
				case InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214_LOD0:
					return PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214.DeserializeArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214_LOD0(inProtocolStream);
				case InternalArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeHexagonPlanetLast_9d078e07b9399aa4cb032287e7e9a327_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeGreyboxBuilding_740dc65917c8b324eb303a2698f2dd1a_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeGreyboxBuilding2_32d6247132758a74088777106e059e9d_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeGreyboxBuilding3_8fbce83bfa2ab394197ba0c36dd48c6e_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypetree1GGJ_dcbe017ddb668d24fbbd84607bebbc08_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypetree2GGJ_6deeb2c1af05aa8418d68271a04a30d0_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypetree3GGJ_aeb6565d66e84134a8bed68b9c23a88c_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypetree_GGJ_3bcf20e841cfdc74388cde29fa1de9ba_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeBuilding1_b4bece24bc468c34587f46fa49fba06f_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypebuilding2_055f8f777c9c41a4d90ba8bc1ab22dae_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeBuilding3_7a150e548341e554686c3ad454e4222c_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeBuilding4_e19425375427f9b488aa3730f7396c91_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypePlayer__char_32_1_555d1695bf1878941bdcea6e7bdd0b10_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypePlayer__char_32_1_555d1695bf1878941bdcea6e7bdd0b10_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypePlayer__char_32_2_75f6611ace5a6a74daa3ea8e6a775feb_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypePlayer__char_32_2_75f6611ace5a6a74daa3ea8e6a775feb_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeTree2_3d52409f49bc3ee4fbe52ae04f61f837_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeTree3_5a772a534f3f2634fb628cceb128b128_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeTree3_5a772a534f3f2634fb628cceb128b128_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeTree3_5a772a534f3f2634fb628cceb128b128_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeTreeRotated_5df1f8a97e35cf4489a4be093fd1f124_GenericScale_LOD0(inProtocolStream);
				default:
					return (null, 0, 0);
			}
		}

		public void WriteComponentUpdate(ICoherenceComponentData data, uint mask, 
			IOutProtocolBitStream protocolStream, Logger logger)
		{
			switch (data.GetComponentType())
			{
				case InternalWorldPosition:
					WorldPosition.Serialize((WorldPosition)data, mask, protocolStream);
					break;
				case InternalWorldOrientation:
					WorldOrientation.Serialize((WorldOrientation)data, mask, protocolStream);
					break;
				case InternalLocalUser:
					LocalUser.Serialize((LocalUser)data, mask, protocolStream);
					break;
				case InternalWorldPositionQuery:
					WorldPositionQuery.Serialize((WorldPositionQuery)data, mask, protocolStream);
					break;
				case InternalArchetypeComponent:
					ArchetypeComponent.Serialize((ArchetypeComponent)data, mask, protocolStream);
					break;
				case InternalPersistence:
					Persistence.Serialize((Persistence)data, mask, protocolStream);
					break;
				case InternalConnectedEntity:
					ConnectedEntity.Serialize((ConnectedEntity)data, mask, protocolStream);
					break;
				case InternalUniqueID:
					UniqueID.Serialize((UniqueID)data, mask, protocolStream);
					break;
				case InternalConnection:
					Connection.Serialize((Connection)data, mask, protocolStream);
					break;
				case InternalGlobal:
					Global.Serialize((Global)data, mask, protocolStream);
					break;
				case InternalGlobalQuery:
					GlobalQuery.Serialize((GlobalQuery)data, mask, protocolStream);
					break;
				case InternalTag:
					Tag.Serialize((Tag)data, mask, protocolStream);
					break;
				case InternalTagQuery:
					TagQuery.Serialize((TagQuery)data, mask, protocolStream);
					break;
				case InternalPreserveChildren:
					PreserveChildren.Serialize((PreserveChildren)data, mask, protocolStream);
					break;
				case InternalGenericPrefabReference:
					GenericPrefabReference.Serialize((GenericPrefabReference)data, mask, protocolStream);
					break;
				case InternalGenericPrefabId:
					GenericPrefabId.Serialize((GenericPrefabId)data, mask, protocolStream);
					break;
				case InternalGenericScale:
					GenericScale.Serialize((GenericScale)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt0:
					GenericFieldInt0.Serialize((GenericFieldInt0)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt1:
					GenericFieldInt1.Serialize((GenericFieldInt1)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt2:
					GenericFieldInt2.Serialize((GenericFieldInt2)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt3:
					GenericFieldInt3.Serialize((GenericFieldInt3)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt4:
					GenericFieldInt4.Serialize((GenericFieldInt4)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt5:
					GenericFieldInt5.Serialize((GenericFieldInt5)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt6:
					GenericFieldInt6.Serialize((GenericFieldInt6)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt7:
					GenericFieldInt7.Serialize((GenericFieldInt7)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt8:
					GenericFieldInt8.Serialize((GenericFieldInt8)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt9:
					GenericFieldInt9.Serialize((GenericFieldInt9)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt0:
					GenericFieldUInt0.Serialize((GenericFieldUInt0)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt1:
					GenericFieldUInt1.Serialize((GenericFieldUInt1)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt2:
					GenericFieldUInt2.Serialize((GenericFieldUInt2)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt3:
					GenericFieldUInt3.Serialize((GenericFieldUInt3)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt4:
					GenericFieldUInt4.Serialize((GenericFieldUInt4)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt5:
					GenericFieldUInt5.Serialize((GenericFieldUInt5)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt6:
					GenericFieldUInt6.Serialize((GenericFieldUInt6)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt7:
					GenericFieldUInt7.Serialize((GenericFieldUInt7)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt8:
					GenericFieldUInt8.Serialize((GenericFieldUInt8)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt9:
					GenericFieldUInt9.Serialize((GenericFieldUInt9)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool0:
					GenericFieldBool0.Serialize((GenericFieldBool0)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool1:
					GenericFieldBool1.Serialize((GenericFieldBool1)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool2:
					GenericFieldBool2.Serialize((GenericFieldBool2)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool3:
					GenericFieldBool3.Serialize((GenericFieldBool3)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool4:
					GenericFieldBool4.Serialize((GenericFieldBool4)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool5:
					GenericFieldBool5.Serialize((GenericFieldBool5)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool6:
					GenericFieldBool6.Serialize((GenericFieldBool6)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool7:
					GenericFieldBool7.Serialize((GenericFieldBool7)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool8:
					GenericFieldBool8.Serialize((GenericFieldBool8)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool9:
					GenericFieldBool9.Serialize((GenericFieldBool9)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat0:
					GenericFieldFloat0.Serialize((GenericFieldFloat0)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat1:
					GenericFieldFloat1.Serialize((GenericFieldFloat1)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat2:
					GenericFieldFloat2.Serialize((GenericFieldFloat2)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat3:
					GenericFieldFloat3.Serialize((GenericFieldFloat3)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat4:
					GenericFieldFloat4.Serialize((GenericFieldFloat4)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat5:
					GenericFieldFloat5.Serialize((GenericFieldFloat5)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat6:
					GenericFieldFloat6.Serialize((GenericFieldFloat6)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat7:
					GenericFieldFloat7.Serialize((GenericFieldFloat7)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat8:
					GenericFieldFloat8.Serialize((GenericFieldFloat8)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat9:
					GenericFieldFloat9.Serialize((GenericFieldFloat9)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble0:
					GenericFieldDouble0.Serialize((GenericFieldDouble0)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble1:
					GenericFieldDouble1.Serialize((GenericFieldDouble1)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble2:
					GenericFieldDouble2.Serialize((GenericFieldDouble2)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble3:
					GenericFieldDouble3.Serialize((GenericFieldDouble3)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble4:
					GenericFieldDouble4.Serialize((GenericFieldDouble4)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble5:
					GenericFieldDouble5.Serialize((GenericFieldDouble5)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble6:
					GenericFieldDouble6.Serialize((GenericFieldDouble6)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble7:
					GenericFieldDouble7.Serialize((GenericFieldDouble7)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble8:
					GenericFieldDouble8.Serialize((GenericFieldDouble8)data, mask, protocolStream);
					break;
				case InternalGenericFieldDouble9:
					GenericFieldDouble9.Serialize((GenericFieldDouble9)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector0:
					GenericFieldVector0.Serialize((GenericFieldVector0)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector1:
					GenericFieldVector1.Serialize((GenericFieldVector1)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector2:
					GenericFieldVector2.Serialize((GenericFieldVector2)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector3:
					GenericFieldVector3.Serialize((GenericFieldVector3)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector0:
					GenericField2dVector0.Serialize((GenericField2dVector0)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector1:
					GenericField2dVector1.Serialize((GenericField2dVector1)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector2:
					GenericField2dVector2.Serialize((GenericField2dVector2)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector3:
					GenericField2dVector3.Serialize((GenericField2dVector3)data, mask, protocolStream);
					break;
				case InternalGenericFieldString0:
					GenericFieldString0.Serialize((GenericFieldString0)data, mask, protocolStream);
					break;
				case InternalGenericFieldString1:
					GenericFieldString1.Serialize((GenericFieldString1)data, mask, protocolStream);
					break;
				case InternalGenericFieldString2:
					GenericFieldString2.Serialize((GenericFieldString2)data, mask, protocolStream);
					break;
				case InternalGenericFieldString3:
					GenericFieldString3.Serialize((GenericFieldString3)data, mask, protocolStream);
					break;
				case InternalGenericFieldString4:
					GenericFieldString4.Serialize((GenericFieldString4)data, mask, protocolStream);
					break;
				case InternalGenericFieldQuaternion0:
					GenericFieldQuaternion0.Serialize((GenericFieldQuaternion0)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity0:
					GenericFieldEntity0.Serialize((GenericFieldEntity0)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity1:
					GenericFieldEntity1.Serialize((GenericFieldEntity1)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity2:
					GenericFieldEntity2.Serialize((GenericFieldEntity2)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity3:
					GenericFieldEntity3.Serialize((GenericFieldEntity3)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity4:
					GenericFieldEntity4.Serialize((GenericFieldEntity4)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity5:
					GenericFieldEntity5.Serialize((GenericFieldEntity5)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity6:
					GenericFieldEntity6.Serialize((GenericFieldEntity6)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity7:
					GenericFieldEntity7.Serialize((GenericFieldEntity7)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity8:
					GenericFieldEntity8.Serialize((GenericFieldEntity8)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity9:
					GenericFieldEntity9.Serialize((GenericFieldEntity9)data, mask, protocolStream);
					break;
				case InternalGenericFieldBytes0:
					GenericFieldBytes0.Serialize((GenericFieldBytes0)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong0:
					GenericFieldLong0.Serialize((GenericFieldLong0)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong1:
					GenericFieldLong1.Serialize((GenericFieldLong1)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong2:
					GenericFieldLong2.Serialize((GenericFieldLong2)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong3:
					GenericFieldLong3.Serialize((GenericFieldLong3)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong0:
					GenericFieldULong0.Serialize((GenericFieldULong0)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong1:
					GenericFieldULong1.Serialize((GenericFieldULong1)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong2:
					GenericFieldULong2.Serialize((GenericFieldULong2)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong3:
					GenericFieldULong3.Serialize((GenericFieldULong3)data, mask, protocolStream);
					break;
				case InternalGenericFieldColor0:
					GenericFieldColor0.Serialize((GenericFieldColor0)data, mask, protocolStream);
					break;
				case InternalGenericFieldColor1:
					GenericFieldColor1.Serialize((GenericFieldColor1)data, mask, protocolStream);
					break;
				case InternalPlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149:
					PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149.Serialize((PlayerHuman_id0_UnityEngine__char_46_Animator_5819893876217580149)data, mask, protocolStream);
					break;
				case InternalPlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214:
					PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214.Serialize((PlayerTree_id1_UnityEngine__char_46_Animator_5624696503662188214)data, mask, protocolStream);
					break;
			}
		}

		private IEntityCommand ReadCommand(uint commandType, IInProtocolBitStream bitStream, Logger logger)
		{
			switch (commandType)
			{
				case Definition.InternalAuthorityRequest:
					return AuthorityRequest.Deserialize(bitStream);
				case Definition.InternalAuthorityTransfer:
					return AuthorityTransfer.Deserialize(bitStream);
				case Definition.InternalQuerySynced:
					return QuerySynced.Deserialize(bitStream);
				case Definition.InternalAdoptOrphan:
					return AdoptOrphan.Deserialize(bitStream);
				case Definition.InternalPersistenceReady:
					return PersistenceReady.Deserialize(bitStream);
				case Definition.InternalGenericCommand:
					return GenericCommand.Deserialize(bitStream);
				default:
					break;
			}

			return default;
		}

		private IEntityInput ReadInput(uint inputType, IInProtocolBitStream bitStream, Logger logger)
		{
			switch (inputType)
			{
				case Definition.InternalPlayerHuman:
					return PlayerHuman.Deserialize(bitStream);
				case Definition.InternalPlayerTree:
					return PlayerTree.Deserialize(bitStream);
				default:
					break;
			}

			return default;
		}

		public (IEntityCommand command, SerializeEntityID entityId, MessageTarget messageTarget)[]
			ReadCommands(IInBitStream bitStream, Logger logger)
		{
			var numMessages = bitStream.ReadUint8();

			var commandData = new (IEntityCommand command, SerializeEntityID entityId, MessageTarget messageTarget)[numMessages];

			for (var i = 0; i < numMessages; i++)
			{
				commandData[i].entityId = DeserializerTools.DeserializeEntityID(bitStream);
				commandData[i].messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
				var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
				var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
				commandData[i].command = ReadCommand(componentType, inBitStream, logger);
			}

			return commandData;
		}

		public (IEntityInput input, long frame, SerializeEntityID entityId)[] 
			ReadInputs(IInBitStream bitStream, Logger logger)
		{
			var numMessages = bitStream.ReadUint8();

			var inputData = new (IEntityInput input, long frame, SerializeEntityID entityId)[numMessages];

			for (var i = 0; i < numMessages; i++)
			{
				inputData[i].entityId = DeserializerTools.DeserializeEntityID(bitStream);
				_ = DeserializerTools.DeserializeMessageTarget(bitStream);
				var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
				var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
				inputData[i].frame = (long)bitStream.ReadUint64();
				inputData[i].input = ReadInput(componentType, inBitStream, logger);
			}

			return inputData;
		}

		public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
		{
			switch (commandType)
			{
				case Definition.InternalAuthorityRequest:
					AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
					break;
				case Definition.InternalAuthorityTransfer:
					AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
					break;
				case Definition.InternalQuerySynced:
					QuerySynced.Serialize((QuerySynced)data, bitStream);
					break;
				case Definition.InternalAdoptOrphan:
					AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
					break;
				case Definition.InternalPersistenceReady:
					PersistenceReady.Serialize((PersistenceReady)data, bitStream);
					break;
				case Definition.InternalGenericCommand:
					GenericCommand.Serialize((GenericCommand)data, bitStream);
					break;
				default:
					break;
			}
		}

		public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
		{
			var inputData = (InputData)data;
			bitStream.WriteLong(inputData.Frame);

			switch (inputType)
			{
				case Definition.InternalPlayerHuman:
					PlayerHuman.Serialize((PlayerHuman)inputData.Input, bitStream);
					break;
				case Definition.InternalPlayerTree:
					PlayerTree.Serialize((PlayerTree)inputData.Input, bitStream);
					break;
				default:
					break;
			}
		}

		public IEntityCommand CreateAuthorityRequest(ClientID requester, AuthorityType authType)
		{
			return new AuthorityRequest((uint)requester, (int)authType);
		}

		public IEntityCommand CreateAdoptOrphanCommand()
		{
			return new AdoptOrphan();
		}

		public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand, 
			out ClientID requester, out AuthorityType authType)
		{
			if (entityCommand is AuthorityRequest request) 
			{
				requester = (ClientID)request.requester;
				authType = (AuthorityType)request.authorityType;

				return true;
			}

			requester = default;
			authType = default;

			return false;
		}

		public IEntityCommand CreateAuthorityTransfer(ClientID newAuthority, bool accepted, AuthorityType authType)
		{
			return new AuthorityTransfer((uint)newAuthority, accepted, (int)authType);
		}

		public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
			out bool transferAccepted, out AuthorityType authType) 
		{
			if (entityCommand is AuthorityTransfer transfer) 
			{
				newAuthority = (ClientID)transfer.newAuthority;
				transferAccepted = transfer.accepted;
				authType = (AuthorityType)transfer.authorityType;

				return true;
			}

			newAuthority = default;
			transferAccepted = default;
			authType = default;

			return false;
		}

		public ICoherenceComponentData GeneratePersistenceData()
		{
			var persistence = new Persistence();

			return persistence;
		}

		public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid)
		{
			var uniqueID = new UniqueID();
			uniqueID.uuid = uuid;

			return uniqueID;
		}

		public ICoherenceComponentData GenerateGlobalQueryComponent()
		{
			return new GlobalQuery();
		}

		public string ExtractCoherenceUUID(ICoherenceComponentData data)
		{
			var uniqueID = (UniqueID)data;
			return uniqueID.uuid;
		}

		public bool IsConnectedEntity(ICoherenceComponentData data)
		{
			return data.GetComponentType() == Definition.InternalConnectedEntity;
		}

		public SerializeEntityID ExtractConnectedEntityID(ICoherenceComponentData data)
		{
			var connectedEntity = (ConnectedEntity)data;

			return connectedEntity.value;
		}

		public string ExtractCoherenceTag(ICoherenceComponentData data)
		{
			var tag = (Tag)data;
			return tag.tag;
		}
	}
}