// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct GenericScale : ICoherenceComponentData
	{
		public Vector3 value;

		public override string ToString()
		{
			return $"GenericScale(value: {value})";
		}

		public uint GetComponentType() => Definition.InternalGenericScale;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (GenericScale)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				value = other.value;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(GenericScale data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.value.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (GenericScale, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
	
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask, null);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeBuildingRot_d7c48c9304a42cb4786538e9ef8284a4_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeBuildingRot1_d3b68f2763ee5354ea6e20ba9fe863b6_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeBuildingRot2_e54e3390c037cdb4ea5c1b0191dd93ff_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeTreeRot_9d98c1c2c8ca66341b697cd88abce46b_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeTreeRot1_f3e71fd7c178b0741a7f8fa2e92e94cb_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeTreeRot2_665e8f2632a4d3a46a693f897bb7ccae_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeTreeRot3_fd4e093c29f40b14ea1af5200044859c_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypePlayerHuman_6d57491473fb68a4a87f6eca2180c0d4_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypeCube_6344a489f82917c4fa01c2adf8b0afd1_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}
		public static (GenericScale, uint, uint?) DeserializeArchetypePlanetIndividualOrigins_fb542973efeb9b8439784d3664e0003a_GenericScale_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new GenericScale();
			if (bitStream.ReadMask())
			{
				val.value = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as GenericScale?;
	
		}
	}
}