// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct PlayerTree_id9_ObjectSpawner_2269046520460430652 : ICoherenceComponentData
	{
		public int objectCounter;

		public override string ToString()
		{
			return $"PlayerTree_id9_ObjectSpawner_2269046520460430652(objectCounter: {objectCounter})";
		}

		public uint GetComponentType() => Definition.InternalPlayerTree_id9_ObjectSpawner_2269046520460430652;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _objectCounter_Min = -2147483648;
		private static readonly int _objectCounter_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (PlayerTree_id9_ObjectSpawner_2269046520460430652)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				objectCounter = other.objectCounter;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(PlayerTree_id9_ObjectSpawner_2269046520460430652 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.objectCounter, _objectCounter_Min, _objectCounter_Max, "PlayerTree_id9_ObjectSpawner_2269046520460430652.objectCounter");
				data.objectCounter = Coherence.Utils.Bounds.Clamp(data.objectCounter, _objectCounter_Min, _objectCounter_Max);
				bitStream.WriteIntegerRange(data.objectCounter, 32, -2147483648);
			}
			mask >>= 1;
		}

		public static (PlayerTree_id9_ObjectSpawner_2269046520460430652, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new PlayerTree_id9_ObjectSpawner_2269046520460430652();
	
			if (bitStream.ReadMask())
			{
				val.objectCounter = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask, null);
		}
		public static (PlayerTree_id9_ObjectSpawner_2269046520460430652, uint, uint?) DeserializeArchetypePlayerTree_6e41740ccd468754ebce2e5459d93cdd_PlayerTree_id9_ObjectSpawner_2269046520460430652_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new PlayerTree_id9_ObjectSpawner_2269046520460430652();
			if (bitStream.ReadMask())
			{
				val.objectCounter = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as PlayerTree_id9_ObjectSpawner_2269046520460430652?;
	
		}
	}
}