// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786 : ICoherenceComponentData
	{
		public string path;
		public int pathDirtyCounter;

		public override string ToString()
		{
			return $"TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786(path: {path}, pathDirtyCounter: {pathDirtyCounter})";
		}

		public uint GetComponentType() => Definition.InternalTreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _pathDirtyCounter_Min = -2147483648;
		private static readonly int _pathDirtyCounter_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				path = other.path;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				pathDirtyCounter = other.pathDirtyCounter;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteShortString(data.path);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.pathDirtyCounter, _pathDirtyCounter_Min, _pathDirtyCounter_Max, "TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786.pathDirtyCounter");
				data.pathDirtyCounter = Coherence.Utils.Bounds.Clamp(data.pathDirtyCounter, _pathDirtyCounter_Min, _pathDirtyCounter_Max);
				bitStream.WriteIntegerRange(data.pathDirtyCounter, 32, -2147483648);
			}
			mask >>= 1;
		}

		public static (TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786();
	
			if (bitStream.ReadMask())
			{
				val.path = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.pathDirtyCounter = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, null);
		}
		public static (TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786, uint, uint?) DeserializeArchetypeTreeRot3_fd4e093c29f40b14ea1af5200044859c_TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786();
			if (bitStream.ReadMask())
			{
				val.path = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.pathDirtyCounter = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000010;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as TreeRot3_id8_Coherence__char_46_Toolkit__char_46_CoherenceNode_2294763835116118786?;
	
		}
	}
}